### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by drewswinburne** [ga-wdi-exercises/project4#430] opened 2016-12-22 19:57 UTC
Having some difficulty deploying with heroku and mlab. Heroku set up 2 databases (called Mongodb and Brown), but neither of them have any collections in them

I've set mongoose to this:

```
mongoose.connect(process.env.MONGOLAB_URI || 'mongodb://localhost/stockticker');
```
I've also included this in my package.json 

```
  "scripts": {
    "start": "node app.js"
  }
```

but then I get errors like this from heroku logs:

```
Listening on 43371
2016-12-22T19:32:09.836032+00:00 app[web.1]: 
2016-12-22T19:32:09.836035+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:265
2016-12-22T19:32:09.836036+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2016-12-22T19:32:09.836037+00:00 app[web.1]:                                       ^
2016-12-22T19:32:09.836862+00:00 app[web.1]: MongoError: failed to connect to server [localhost:27017] on first connect
```

and 

```
2016-12-22T19:32:09.855120+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
```

Is it still trying to connect to localhost? and should it be trying to start remotely with 'npm start'? or something else?

**Comment by drewswinburne** [comment] 2016-12-22 20:08
I did this:

```
heroku config | grep MONGODB_URI
```
and got URI, but I'm not sure what I am supposed to do with it, actually

**Comment by superbuggy** [comment] 2016-12-22 20:10
you can access that that MONGODB_URI with process.env.MONGODB_UI

**Comment by superbuggy** [comment] 2016-12-22 20:10
it's just name-spaced under process.env

**Comment by superbuggy** [comment] 2016-12-22 20:11
```
2016-12-22T19:32:09.836862+00:00 app[web.1]: MongoError: failed to connect to server [localhost:27017] on first connect
```

This error is caused by your schema/connection file, I'd guess

**Comment by superbuggy** [comment] 2016-12-22 20:13
change LAB to DB
```
mongoose.connect(process.env.MONGOLAB_URI || 'mongodb://localhost/stockticker');
```
to
```
mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost/stockticker');
```

Sorry!

**Comment by superbuggy** [comment] 2016-12-22 20:13
It saw that `process.env.MONGOLAB_URI` was undefined and returned `'mongodb://localhost/stockticker'` to `mongoose.connect`

**Comment by drewswinburne** [comment] 2016-12-22 20:25
oh wow, just a typo

**Comment by superbuggy** [comment] 2016-12-22 20:27
I've seen that one a ton, haha. Is there a mistake in a lesson plan?

**Comment by drewswinburne** [comment] 2016-12-22 20:30
No but there's a mistake in this otherwise helpful walkthrough: http://www.tilcode.com/deploying-a-mean-stack-app-to-heroku/

**Comment by superbuggy** [comment] 2016-12-22 20:35
aha! thanks Drew. Closing for now-- reopen if needed.

**Closed as completed by superbuggy** 2016-12-22 20:35 UTC
