### ISSUE TITLE
One last issue! Angular not rendering on mobile

### ISSUE THREAD

**Issue by khoitle** [ga-wdi-exercises/project4#397] opened 2016-12-02 15:34 UTC
I used the MEAN stack and the only page that renders on mobile is the only page I did the front end in express. Any ideas?

**Comment by nolds9** [comment] 2016-12-02 15:36
have you gone to `/#/` to hit your first state?

**Comment by khoitle** [comment] 2016-12-02 15:37
yeah

**Comment by khoitle** [comment] 2016-12-02 15:37
The nav bar done via bootstrap is rendered, and the drop down bar has all the database information

**Comment by jshawl** [comment] 2016-12-02 15:37
any error messages? any screenshots? how can i reproduce? are you iphone?

**Comment by khoitle** [comment] 2016-12-02 15:38
Is it because of these CDN's? Do I have to use the newest version or anything like that?

![image](https://cloud.githubusercontent.com/assets/20734065/20839663/6c20043a-b87b-11e6-9f84-98aa310074b6.png)

**Comment by khoitle** [comment] 2016-12-02 15:39
This is the "mobile" view via chrome on a desktop
![image](https://cloud.githubusercontent.com/assets/20734065/20839700/97cae4ba-b87b-11e6-97af-2b4541f6bef2.png)

**Comment by khoitle** [comment] 2016-12-02 15:42
And here's what it looks like on an actual phone
![image](https://cloud.githubusercontent.com/assets/20734065/20839808/f726c582-b87b-11e6-8dd5-9a39dc3f9a35.png)

**Comment by nolds9** [comment] 2016-12-02 15:46
Is it possible because you are using an older version of IOS safari, which does not support arrow functions http://caniuse.com/#search=arrow%20functions

**Comment by khoitle** [comment] 2016-12-02 15:47
Oh cool! That tells me i need to upgrade my phone haha. Thanks a bunch!

**Comment by nolds9** [comment] 2016-12-02 15:50
It works on my phone! Had to make sure that there was a `/#/` in the url

**Comment by khoitle** [comment] 2016-12-02 15:52
Yeah I got scared that my app didnt work on mobile but then i remembered I have a pretty old phone. phew!

**Comment by amaseda** [comment] 2016-12-02 16:15
@KhoiLe89 :+1: Good to go? Can we close this issue?

**Closed as completed** 2016-12-16 14:07 UTC
Labels: waiting-on-student-response
